include $(GOROOT)/src/Make.inc

TARG=aws/sdb
GOFILES=\
	service.go\
	consts.go\
	response.go\
	domain.go\
	attribute.go\
#	handler.go\
#	response.go\

DEPS=../

CLEANFILES+=\

include $(GOROOT)/src/Make.pkg


