include $(GOROOT)/src/Make.inc

TARG=aws/sqs
GOFILES=\
	\
	new_queue.go\
	new_service.go\
	request.go\
#	service.go\
#	message.go\
#	error.go\
#	sqs_types.go\

DEPS=\
	../\
	../awsconn\

include $(GOROOT)/src/Make.pkg

