include $(GOROOT)/src/Make.inc

TARG=awstool
GOFILES=main.go\

DEPS=\
	../s3/util/\
	../sqs/util/\
	../sdb/util/\
	../ec2/util/\
	../elb/util/\
	../flags/\
	./common/\

CLEANFILES+=\

include $(GOROOT)/src/Make.cmd

